# Generated by Django 5.2.1 on 2025-05-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('number_of_guests', models.IntegerField()),
                ('section', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
